datasets:
    classes:
        num_classes: 80
        classes_txt: /path/to/classes.txt
    sets:
        train:
            csv: /path/to/train.csv
            aug: configs/augmentations/train_aug.yaml

        val:
            csv: /path/to/val.csv
            aug: configs/augmentations/test_aug.yaml

        test:
            csv: /path/to/test.csv
            aug: configs/augmentations/test_aug.yaml
    viz: true

model:
    architecture: resnet18
    weights: pretrained  # "pretrained" or path to weights

training:
    save_context: 1st-run
    save_dir: /path/to/output/dir
    device: 'cuda:0'
    data_num_workers: 4
    batch_size: 32
    optimizer: 
        SGD:
            lr: 0.01
            momentum: 0.9
        # Adam:
        #     lr: 0.01
        #     betas:
        #         - 0.9
        #         - 0.999
        #     eps: 1.0e-8
        #     weight_decay: 0
        #     amsgrad: false
    scheduler:
        StepLR:
            step_size: 10
            gamma: 0.1
    num_epochs: 15 
    early_stopping: 3 # num of times with no improved val loss before ending
    verbose_steps: 10 # num of steps before printing loss info 
