- RandomResizedCrop: 
    size: 224
- RandomHorizontalFlip: 
- ColorJitter: 
    brightness:
        - 0.5
        - 2.0
    contrast:
        - 0.5
        - 2.0
# - RandomAffine: 
#     degrees: 35
#     translate: null
#     scale:
#         - 0.5
#         - 1.25
#     shear: null
#     resample: false
#     fillcolor: 0
- ToTensor: 
- Normalize:
    mean: 
        - 0.485
        - 0.456
        - 0.406
    std:
        - 0.229
        - 0.224
        - 0.225
